version: "3.9"
services:
  clothing-model: # tf-serving model
    image: tf-serving:latest
  gateway: # flask gateway service
    image: gateway-service:latest # new version
    environment:
      - TF_SERVING_HOST=clothing-model:8500 # look for clothing model and port 8500
    ports: # map host machine with gateway
      - "9696:9696"