version: "3.9"
services:
  clothing-model: # tf-serving model
    image: clothing-model:v1
  gateway: # flask gateway service
    image: fashion-gateway:v1 # new version
    build:
      context: .
      dockerfile: image-gateway.dockerfile
    environment:
      - TF_SERVING_HOST=clothing-model:8500 # look for clothing model and port 8500
    ports: # map host machine with gateway
      - "9696:9696"
    
  image-frontend:
    image: fashion-frontend:latest
    build:
      context: .
      dockerfile: image-frontend.dockerfile
    ports:
      - "8501:8501"
    environment:
      - GATEWAY_URL=http://gateway:9696/predict
    depends_on:
      - gateway